import type { Filter, FilterPresetDefinition } from '$types/filter';

export const DEFAULT_FILTER_PRESET_DEFINITIONS: FilterPresetDefinition[] = [
  {
    presetId: 'today',
    category: 'date',
    name: 'Today',
    icon: 'calendar-check',
    combinator: 'all',
    sortOrder: 100,
    criteria: [
      { field: 'dueDate', op: 'today' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { dueDate: 'today' },
  },
  {
    presetId: 'overdue',
    category: 'date',
    name: 'Overdue',
    icon: 'clock',
    combinator: 'all',
    sortOrder: 200,
    criteria: [
      { field: 'dueDate', op: 'beforeToday' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
  },
  {
    presetId: 'scheduled',
    category: 'date',
    name: 'Scheduled',
    icon: 'calendar-clock',
    combinator: 'all',
    sortOrder: 300,
    criteria: [
      { field: 'dueDate', op: 'exists' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
  },
  {
    presetId: 'this-week',
    category: 'date',
    name: 'This Week',
    icon: 'calendar-days',
    combinator: 'all',
    sortOrder: 400,
    criteria: [
      { field: 'dueDate', op: 'withinDays', value: 7 },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
  },
];

export const FILTER_PRESET_DEFINITIONS: FilterPresetDefinition[] = [
  ...DEFAULT_FILTER_PRESET_DEFINITIONS,
  {
    presetId: 'in-progress',
    category: 'status',
    name: 'In Process',
    icon: 'timer',
    combinator: 'all',
    sortOrder: 500,
    criteria: [{ field: 'status', op: 'is', value: 'in-process' }],
    taskDefaults: { status: 'in-process' },
  },
  {
    presetId: 'tomorrow',
    category: 'date',
    name: 'Tomorrow',
    icon: 'calendar',
    combinator: 'all',
    sortOrder: 600,
    criteria: [
      { field: 'dueDate', op: 'tomorrow' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { dueDate: 'tomorrow' },
  },
  {
    presetId: 'no-start-date',
    category: 'date',
    name: 'No Start Date',
    icon: 'calendar-minus',
    combinator: 'all',
    sortOrder: 750,
    criteria: [
      { field: 'startDate', op: 'empty' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { startDate: 'none' },
  },
  {
    presetId: 'no-due-date',
    category: 'date',
    name: 'No Due Date',
    icon: 'calendar-off',
    combinator: 'all',
    sortOrder: 700,
    criteria: [
      { field: 'dueDate', op: 'empty' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { dueDate: 'none' },
  },
  {
    presetId: 'high-priority',
    category: 'priority',
    name: 'High Priority',
    icon: 'flag',
    combinator: 'all',
    sortOrder: 800,
    criteria: [
      { field: 'priority', op: 'is', value: 'high' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { priority: 'high' },
  },
  {
    presetId: 'medium-priority',
    category: 'priority',
    name: 'Medium Priority',
    icon: 'flag',
    combinator: 'all',
    sortOrder: 900,
    criteria: [
      { field: 'priority', op: 'is', value: 'medium' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { priority: 'medium' },
  },
  {
    presetId: 'low-priority',
    category: 'priority',
    name: 'Low Priority',
    icon: 'flag',
    combinator: 'all',
    sortOrder: 1000,
    criteria: [
      { field: 'priority', op: 'is', value: 'low' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { priority: 'low' },
  },
  {
    presetId: 'no-priority',
    category: 'priority',
    name: 'No Priority',
    icon: 'flag',
    combinator: 'all',
    sortOrder: 1100,
    criteria: [
      { field: 'priority', op: 'is', value: 'none' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
    taskDefaults: { priority: 'none' },
  },
  {
    presetId: 'needs-action',
    category: 'status',
    name: 'Needs Action',
    icon: 'rotate-ccw',
    combinator: 'all',
    sortOrder: 600,
    criteria: [{ field: 'status', op: 'is', value: 'needs-action' }],
    taskDefaults: { status: 'needs-action' },
  },
  {
    presetId: 'completed',
    category: 'status',
    name: 'Completed',
    icon: 'check',
    combinator: 'all',
    sortOrder: 700,
    criteria: [{ field: 'status', op: 'is', value: 'completed' }],
    taskDefaults: { status: 'completed' },
  },
  {
    presetId: 'cancelled',
    category: 'status',
    name: 'Cancelled',
    icon: 'ban',
    combinator: 'all',
    sortOrder: 800,
    criteria: [{ field: 'status', op: 'is', value: 'cancelled' }],
    taskDefaults: { status: 'cancelled' },
  },
  {
    presetId: 'untagged',
    category: 'organization',
    name: 'Untagged',
    icon: 'tag',
    combinator: 'all',
    sortOrder: 900,
    criteria: [
      { field: 'tags', op: 'empty' },
      { field: 'status', op: 'notIn', value: ['completed', 'cancelled'] },
    ],
  },
  {
    presetId: 'recently-completed',
    category: 'date',
    name: 'Recently Completed',
    icon: 'check-square',
    combinator: 'all',
    sortOrder: 1000,
    criteria: [
      { field: 'completedAt', op: 'withinDays', value: 7 },
      { field: 'status', op: 'is', value: 'completed' },
    ],
  },
  {
    presetId: 'recently-modified',
    category: 'date',
    name: 'Recently Modified',
    icon: 'sparkles',
    combinator: 'all',
    sortOrder: 500,
    criteria: [{ field: 'modifiedAt', op: 'withinDays', value: 7 }],
  },
];

export const DEFAULT_FILTER_DEFINITIONS: Array<FilterPresetDefinition & Pick<Filter, 'id'>> =
  DEFAULT_FILTER_PRESET_DEFINITIONS.map((filter, index) => ({
    ...filter,
    id: `default-filter-${filter.presetId}`,
    sortOrder: (index + 1) * 100,
  }));

export const getFilterPresetId = (filter: Pick<Filter, 'presetId'>) => filter.presetId;
